app { job = "mr-lucene-shards" }

mr {
  inputList = "s3a://cs-441-bucket/input/pdf_list_small.txt"
  outputDir = "s3a://cs-441-bucket/outputs/mr_partfiles"   # MR text output if any; harmless to leave
  shards    = 2
}

# Reducers copy Lucene shard directories here:
msr.output.dir = "s3a://cs-441-bucket/outputs/index_shards_mr_out"

embed {
  model    = "mxbai-embed-large"
  maxChars = 1000
  overlap  = 200
  batch    = 8
}
msr.ollama.host = "http://127.0.0.1:11434"
